/**
 * Huffman encoding for a Markov process, generated by by <code>generateeHufmanMarkov</code>.
 *
 * To store a Morkov process we need a Huffman encoding for the steady state distribution, and a Huffman encoding for
 * each symbol in the alphabet (i.e. each state in the Markov process)
 */
public class HuffmanMarkov {

	Huffman		steady;			// huffman for steady state distribution
	Huffman[]	state;			// huffman given that system is in state[k]
	Markov		markov;

	public HuffmanMarkov(Markov markov) {
		state = new Huffman[Distribution.RANGE];
		this.markov = markov;
	}

	public static HuffmanMarkov generate(Markov markov) {

		HuffmanMarkov result = new HuffmanMarkov(markov);

		// Generate Huffman encoding for steady state distribution (same as random variable distribution)
		result.steady = Huffman.generate(markov.steady);

		// For each state, k, generate the Huffman encoding using the (kth) distribution in the Markov process
		for (int k = 0; k < Distribution.RANGE; k++) {
			if (markov.steady.p[k] > 0) {
				result.state[k] = Huffman.generate(markov.state[k]);
			}
		}

		return result;
	}


	/**
	 * Calculate the average codeword length, L(C), in a Huffman encoding.
	 *
	 * @return L(C)
	 */
	public double codewordLength() {
		double sum = 0;

		// First symbol is encoded using steady state distribution
		double firstSymbolLength = steady.codewordLength();

		// Subsequent symbols are encoded using state-dependent distributions
		double subsequentSymbolLength = 0;
		for (int k = 0; k < Distribution.RANGE; k++) {
			if (markov.steady.p[k] > 0 && state[k] != null) {
				subsequentSymbolLength += markov.steady.p[k] * state[k].codewordLength();
			}
		}

		// For a long message, the first symbol's contribution becomes negligible
		// We approximate the average codeword length as the weighted sum of state-dependent lengths
		sum = subsequentSymbolLength;

		return sum;
	}

	/**
	 * Encode a message using Huffamn encoding.
	 *
	 * @param source
	 *            Original message to be encoded
	 *
	 * @return Message encoded using Huffman encoding.
	 */
	public String encode(String source) {

		StringBuilder result = new StringBuilder();

		if (source.length() > 0) {
			// encode the first symbol using steady state distribution
			char firstChar = source.charAt(0);
			if (firstChar < Distribution.RANGE && steady.codewords[firstChar] != null) {
				result.append(steady.codewords[firstChar]);
			}

			// encode the subsequent symbols using state dependent distribution
			for (int i = 0; i < source.length() - 1; i++) {
				char current = source.charAt(i);
				char next = source.charAt(i + 1);

				if (current < Distribution.RANGE && next < Distribution.RANGE &&
						state[current] != null && state[current].codewords[next] != null) {
					result.append(state[current].codewords[next]);
				}
			}
		}

		return result.toString();
	}

	/**
	 * Decode a message using Huffamn encoding.
	 *
	 * @param encoded
	 *            Encoded message to be decoded
	 *
	 * @return Message decoded using Huffman encoding.
	 */
	public String decode(String encoded) {

		StringBuilder result = new StringBuilder();

		if (encoded.length() > 0) {
			int position = 0;

			// Decode first symbol using the steady state encoding tree
			Node current = steady.tree;
			while (position < encoded.length() && !current.isLeaf()) {
				char bit = encoded.charAt(position++);
				if (bit == '0') {
					current = current.left;
				} else {
					current = current.right;
				}
			}

			if (current.isLeaf()) {
				char decodedChar = (char) current.ord;
				result.append(decodedChar);

				// decode the encoded message bit by bit using appropriate state-dependent tree
				while (position < encoded.length()) {
					current = state[decodedChar].tree;

					while (position < encoded.length() && !current.isLeaf()) {
						char bit = encoded.charAt(position++);
						if (bit == '0') {
							current = current.left;
						} else {
							current = current.right;
						}
					}

					if (current.isLeaf()) {
						decodedChar = (char) current.ord;
						result.append(decodedChar);
					}
				}
			}
		}

		return result.toString();
	}
}