import java.util.PriorityQueue;			// used in generating Huffman encoding (want to order symbols in decreasing prob)
import java.util.Stack;					// used in generating Huffman encoding (traverse completed tree to build codewords) 


/**
 * Huffman encoding for a RV distribution, generated by <code>generateeHufman</code>.
 *
 * For efficient encoding and decoding the codewords are stored twice. For encoding: The array <code>codewords</code> is
 * a simple lookup using the character ACSII code as index. For decoding: The binary tree <code>tree</code> is used to
 */
public class Huffman {

	Node			tree;		// root node in Huffman tree (used for decoding)
	String[]		codewords;	// array of codewords (used for encoding)
	Distribution	rv;		// distribution used to generate Huffman codewords

	public Huffman(Distribution rv) {
		tree = null;
		codewords = new String[Distribution.RANGE];
		this.rv = rv;
	}


	/**
	 * Generate Huffman tree and codewords for given probability distribution.
	 *
	 * The input probability distribution may have entries with zero probabilities. The resulting codewords for these
	 * symbols is null.
	 *
	 * @param p
	 *            array of probability (could contain zero values)
	 *
	 * @return array of codewords (null for symbol with zero probability)
	 */
	public static Huffman generate(Distribution rv) {

		Huffman result = new Huffman(rv);

		// populate priority queue by adding entries with non-zero probability
		PriorityQueue<Node> queue = new PriorityQueue<>();
		for (int i = 0; i < Distribution.RANGE; i++) {
			if (rv.p[i] > 0) {
				queue.add(new Node(i, rv.p[i], null, null));
			}
		}

		// Repeatedly merge smallest probability symbols until only one entry
		while (queue.size() > 1) {
			Node left = queue.poll();
			Node right = queue.poll();
			Node parent = new Node(-1, left.p + right.p, left, right);
			queue.add(parent);
		}

		// store top of queue as root node in Huffman tree
		if (!queue.isEmpty()) {
			result.tree = queue.poll();
		}

		// Traverse tree to build codewords
		if (result.tree != null) {
			Stack<Node> nodeStack = new Stack<>();
			nodeStack.push(result.tree);
			result.tree.codeword = "";

			while (!nodeStack.isEmpty()) {
				Node node = nodeStack.pop();

				if (node.isLeaf()) {
					result.codewords[node.ord] = node.codeword;
				} else {
					if (node.right != null) {
						node.right.codeword = node.codeword + "1";
						nodeStack.push(node.right);
					}
					if (node.left != null) {
						node.left.codeword = node.codeword + "0";
						nodeStack.push(node.left);
					}
				}
			}
		}

		return result;
	}

	/**
	 * Calculate the average codeword length, L(C), in a Huffman encoding.
	 *
	 * @return L(C)
	 */
	public double codewordLength() {

		double sum = 0;

		for (int i = 0; i < Distribution.RANGE; i++) {
			if (codewords[i] != null && rv.p[i] > 0) {
				sum += rv.p[i] * codewords[i].length();
			}
		}

		return sum;
	}

	/**
	 * Encode a message using Huffamn encoding.
	 *
	 * @param source
	 *            Original message to be encoded
	 *
	 * @return Message encoded using Huffman encoding.
	 */
	public String encode(String source) {

		StringBuilder result = new StringBuilder();

		// source message is encoded symbol by symbol . . .
		for (int i = 0; i < source.length(); i++) {
			char c = source.charAt(i);
			if (c < Distribution.RANGE && codewords[c] != null) {
				result.append(codewords[c]);
			}
		}

		return result.toString();
	}

	/**
	 * Decode a message using Huffamn encoding.
	 *
	 * @param encoded
	 *            Encoded message to be decoded
	 *
	 * @return Message decoded using Huffman encoding.
	 */
	public String decode(String encoded) {

		StringBuilder result = new StringBuilder();

		// decoding starts at root of Huffman tree
		Node current = tree;

		// We decode the encoded message bit by bit . . .
		for (int i = 0; i < encoded.length(); i++) {
			char bit = encoded.charAt(i);

			if (bit == '0') {
				current = current.left;
			} else {
				current = current.right;
			}

			// if at a leaf node then we have decoding a symbol
			if (current.isLeaf()) {
				result.append((char)current.ord);
				current = tree; // Go back to root
			}
		}

		return result.toString();
	}
}


/**
 * Node used to construct the Huffman code tree.
 *
 * On creation the node just stores the ASCII value of the character and its probability. On completion of the Huffman
 * tree the leaf nodes will store the codeword.
 */
class Node implements Comparable<Node> {
	int		ord;				// ASCII value of character/symbol
	double	p;					// probability
	String	codeword	= "";	// huffman codeword
	Node	left;
	Node	right;

	Node(int id, double p, Node left, Node right) {
		this.ord = id;
		this.p = p;
		this.left = left;
		this.right = right;
	}

	/**
	 * This method allows the use of a PriorityQueue to keep the nodes sorted in non-decreasing probability.
	 */
	@Override
	public int compareTo(Node other) {

		return (int) Math.signum(this.p - other.p);
	}

	/**
	 * Tests if node contains any child nodes.
	 *
	 * In the Huffman tree each symbol is contained in a single leaf node - important for decoding.
	 *
	 * @return true if node does not contain child nodes.
	 */
	public boolean isLeaf() {
		return (left == null && right == null);
	}


	/**
	 * Used for DEBUG output
	 */
	public String toString() {
		return String.format("{id:%d, c:%s, p:%f, l:%s, r:%s}", ord, codeword, p, left, right);
	}

}